### ISSUE TITLE
Can't execute Zyne in Linux

### ISSUE THREAD

**Issue by tank-trax** [belangeo/zyne#5]
Using Debian Buster 10.3

```
python3 Zyne.py 
Traceback (most recent call last):
  File "Zyne.py", line 4, in <module>
    import Resources.audio as audio
  File "/home/studio/dev/extras/zyne/Resources/audio.py", line 8, in <module>
    from pyo64 import *
  File "/usr/lib/python3/dist-packages/pyo64.py", line 29, in <module>
    from pyo import *
  File "/usr/local/lib/python3.7/dist-packages/pyo-1.0.1-py3.7-linux-x86_64.egg/pyo/__init__.py", line 28, in <module>
    from .lib import analysis as analysis
  File "/usr/local/lib/python3.7/dist-packages/pyo-1.0.1-py3.7-linux-x86_64.egg/pyo/lib/analysis.py", line 32, in <module>
    from ._core import *
  File "/usr/local/lib/python3.7/dist-packages/pyo-1.0.1-py3.7-linux-x86_64.egg/pyo/lib/_core.py", line 55, in <module>
    from .._pyo64 import *
ModuleNotFoundError: No module named 'pyo._pyo64'

```

**Comment by belangeo** [comment]
Did you compile pyo with the flag `--use-double` ? It is needed to compile 64-bit (sample precision, not architecture!) version of pyo.

**Comment by tank-trax** [comment]
I tried that and now am getting
```
python Zyne.py 
Traceback (most recent call last):
  File "Zyne.py", line 4, in <module>
    import Resources.audio as audio
  File "~/dev/extras/zyne/Resources/audio.py", line 10, in <module>
    from pyotools import PWM, VCO
ImportError: No module named pyotools
```

**Comment by belangeo** [comment]
Oh yes, you also need to install pyo-tools, a set of ready to use audio classes built with pyo: https://github.com/belangeo/pyo-tools

**Comment by tank-trax** [comment]
I did install them after my comment. :-) Do I need to rebuild pyo?

**Comment by belangeo** [comment]
Nope!

**Comment by tank-trax** [comment]
I am not able to connect using JACK, 

PyoServerStateException: The Server must be booted before creating any audio object.

How does one start the pyo server?

Rebuilt it with JACK

`python3 setup.py build --use-double --use-jack`

**Comment by tank-trax** [comment]
Both Cecilia and Zyne work with JACK now. Thanks!

Extra note: SoundGrain can connect with JACK using
`export PYO_SERVER_AUDIO=jack`
